- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
Port version update to develop
> chore: updated version 0.2.0

- contributing/publishing.md
- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/src/tests/codeCoverage.ts
- packages/apex-node/test/streaming/streamingClient.test.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/test/tests/codeCoverage.test.ts
- packages/apex-node/test/tests/syncTests.test.ts
> Port pr v0.2.1

- packages/apex-node/package.json
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/src/commands/force/apex/execute.ts
- packages/plugin-apex/src/commands/force/apex/log/get.ts
- packages/plugin-apex/src/commands/force/apex/log/list.ts
- packages/plugin-apex/src/commands/force/apex/test/report.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/yarn.lock
bump @salesforce/core to 2.21.0
> chore: bump @salesforce/core to 2.21.0

- packages/apex-node/package.json
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
> chore: bump salesforce core

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
> chore: updated version 0.2.1

- packages/apex-node/package.json
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
bump @salesforce/core to 2.23.2
> bump @salesforce/core to 2.23.2

- packages/apex-node/package.json
- packages/apex-node/src/execute/executeService.ts
- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/src/tests/constants.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/src/commands/force/apex/execute.ts
- packages/plugin-apex/src/commands/force/apex/log/get.ts
- packages/plugin-apex/src/commands/force/apex/log/list.ts
- packages/plugin-apex/src/commands/force/apex/test/report.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/yarn.lock
Port to main for releasing v0.2.2
> Port v0.2.2

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
> chore: updated version 0.2.2 (#203)

- .circleci/config.yml
> fix: wait for dist tags

- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/streaming/types.ts
- packages/apex-node/test/streaming/streamingClient.test.ts
See https://salesforce.quip.com/7bpYAL6T3aNF
@W-9262393@
> fix: fix streaming client errors

- .circleci/config.yml
- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/streaming/types.ts
- packages/apex-node/test/streaming/streamingClient.test.ts
Port to main for releasing v0.2.3
> Port v0.2.3

- .vscode/tasks.json
- package.json
- packages/apex-node/src/i18n/i18n.ts
- packages/apex-node/src/index.ts
- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/src/tests/index.ts
- packages/apex-node/src/tests/testService.ts
- packages/apex-node/src/tests/types.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/test/tests/syncTests.test.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/src/reporters/util.ts
- packages/plugin-apex/test/commands/force/apex/test/run.test.ts
- yarn.lock
This PR adds the ability to exit Apex test runs early based on certain configurations. Exiting the test run early will return the the test run id to the user. Apex tests should exit early if:
--resultformat is not specified and we're only outputting the test run id
--json is specified without the result format flag
https://github.com/forcedotcom/salesforcedx-vscode/issues/3164
@W-9312882@
> feat: exit Apex test runs early 

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
> Port v0.2.3 to develop

- .circleci/config.yml
- .vscode/tasks.json
- package.json
- packages/apex-node/src/i18n/i18n.ts
- packages/apex-node/src/index.ts
- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/src/tests/index.ts
- packages/apex-node/src/tests/testService.ts
- packages/apex-node/src/tests/types.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/test/tests/syncTests.test.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/src/reporters/util.ts
- packages/plugin-apex/test/commands/force/apex/test/run.test.ts
- yarn.lock
Port 0.2.4 from develop to main
> Port pr v0.2.4

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
> chore: updated 0.2.4

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
Port version bump from main to develop.
> chore: updated 0.2.4 (#225)

- .circleci/config.yml
> Port PR for v0.2.5

- .circleci/config.yml
> fix: check npm registry

- packages/apex-node/package.json
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
This PR bumps @salesforce/core to 2.25.1.
@W-9765184@
There is no change in functionality.
There is no change in functionality.
> chore: bump @salesforce/core to 2.25.1

- .circleci/config.yml
- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
> Port v0.2.7 to develop

- packages/apex-node/package.json
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
update @salesforce/core version to 2.28.0
> chore: update @salesforce/core version

- packages/apex-node/package.json
- packages/apex-node/src/i18n/i18n.ts
- packages/apex-node/src/logs/constants.ts
- packages/apex-node/src/logs/index.ts
- packages/apex-node/src/logs/logService.ts
- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/src/tests/codeCoverage.ts
- packages/apex-node/src/tests/constants.ts
- packages/apex-node/src/tests/utils.ts
- packages/apex-node/src/utils/authUtil.ts
- packages/apex-node/src/utils/dateUtil.ts
- packages/apex-node/src/utils/traceFlags.ts
- packages/apex-node/src/utils/types.ts
- packages/apex-node/test/logs/logService.test.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/test/tests/codeCoverage.test.ts
- packages/apex-node/test/utils/traceFlags.test.ts
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/test/commands/force/apex/test/run.test.ts
- packages/plugin-apex/yarn.lock
> Port pr v0.2.9

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
> chore: updated version 0.2.9

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
> chore: updated version 0.3.0

- contributing/publishing.md
Adds some additional steps to the "Post Publish" section.
@W-10020820@
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000FeMfZYAV/view
> fix: added additional steps to post-publishing

- .circleci/config.yml
changes to publish as part of every merge to main
@W-10054133@
> chore: changes to publish as part of every merge to main @W-10054133@

- packages/apex-node/package.json
- packages/apex-node/test/streaming/streamingClient.test.ts
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
Duplicate PR for https://github.com/forcedotcom/salesforcedx-apex/pull/259 to run CI/CD jobs to test and release.
> feat: bump version of core and faye

- .circleci/config.yml
Remove node 10 and add node 14 jobs
N/A
Node 10 jobs were run in CI/CD
Node 14 jobs will be run in CI/CD
> Remove node 10 and add node 14 jobs

- .circleci/config.yml
- .github/CODEOWNERS
Port release changes from develop to main
> Port release changes from develop to main @W-10054133@

- contributing/publishing.md
Doc updates to reflect the new release process
@W-10054133@
N/A
N/A
> docs: update release process doc @W-10054133@

- .github/CODEOWNERS
Update CODEOWNERS with GUSINFO
@W-9377468@
N/A
No functionality change
> Update CODEOWNERS with GUSINFO

- .circleci/config.yml
Testing to use context for env variables
Env variables are defined in project settings.
Env variables are now defined in a context at Organizational settings.
> Ra/consolidate keys_test_PR

- package.json
- packages/apex-node/package.json
- packages/apex-node/src/reporters/coverageReporter.ts
- packages/apex-node/yarn.lock
- packages/plugin-apex/yarn.lock
- yarn.lock
Corrects the means in which source files are located in the file system
@W-11173201@
glob was called for each covered class or trigger
glob is now called one to find all classes and triggers. Resulting array is used to provide path to source.
> fix: perf issue while mapping coverage to source

- packages/apex-node/package.json
- packages/apex-node/test/execute/executeService.test.ts
- packages/apex-node/test/streaming/streamingClient.test.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/test/tests/codeCoverage.test.ts
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
unpin `@salesforce/command` and fix tests. Note that pinning the module caused issues for cli b/c it results in long imports that break the circleci build. 
@W-11385241@
> fix: add caret to command and fix tests

- package.json
> feat!: bump core to v5

- package.json
> feat: bump core to v5

- package.json
- yarn.lock
> fix: revert deps core and kit

- package.json
Bump the version in package.json to 7.0.0 for the major release
@W-16083844@
> chore: bump version for major release

- .github/dependabot.yml
- .github/workflows/automerge.yml
@W-16038627@
add dependabot config and automerge workflow
> build: add dependabot

- .github/workflows/create-github-release.yml
> build: comment out docs step for now

- package.json
- src/reporters/humanFormatTransform.ts
- src/reporters/humanReporter.ts
- src/tests/asyncTests.ts
- test/reporters/humanFormatTransform.test.ts
- test/reporters/humanReporter.test.ts
- yarn.lock
Takes into account concise option for test setup section
- Test setup section doesn't show up if concise is true
[skip-validate-pr]
> feat: consider concise feature for test setup section

- package.json
- yarn.lock
[skip-validate-pr]
adds resolution to move `whatwg-url` to latest to remove `punycode` deprecation warnings
> fix: bump jsforce, add resolution

- .github/workflows/onRelease.yml
- .github/workflows/releaseWithCoreBundle.yml
- package.json
- Adds a check to skip publish job if it's a beta release
@W-16304265@
> chore: modify workflows to skip publish upon beta release 

- package.json
- src/tests/asyncTests.ts
- src/tests/testService.ts
- src/tests/types.ts
- test/testData.ts
- test/tests/asyncTests.test.ts
- yarn.lock
This PR is to add a fork on the existing apex run library, so that if it is running flow test, we will:
1. make sure it is running flow test
2. we will pull test result from FlowTestResult 
it is adding new logic for flow test run. Here is the [PRD](https://docs.google.com/document/d/1CeVSAbVp6QM-y2f2i5tEbMpPTHuN2TeHzJpysyn0uyw/edit?pli=1&tab=t.0#heading=h.xvjl1gujfq9n)
#<Insert GitHub Issue>, @W-17543839@
Only Apex test run is supported.
<insert gif and/or summary>
both apex test run and flow test run will be supported. 
<insert gif and/or summary>
To run Flow test at local:
1. clone https://github.com/salesforcecli/plugin-flow to local
2. clone this repo to your local.
3. link these 2 repo (yarn link)
4. create devhub and create flowtest on this devhub (make sure you have sfdx installed …
> @W-17543839 adding logic to support flow run test

- .github/CODEOWNERS
- LICENSE.txt
- how_to_license.md
This pull request includes updates to licensing information and changes to code ownership. The most significant updates involve adopting the BSD 3-Clause License for the project and documenting licensing practices, as well as updating the code ownership team for the repository.
* [`LICENSE.txt`](diffhunk://#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7L1-R29): Updated the project's license to the BSD 3-Clause License, replacing the previous copyright notice and terms.
* [`how_to_license.md`](diffhunk://#diff-d2ce9205dde0c17fc8e4900a0be3360290d146b2e9bdfcc006d693ae12cc321dR1-R66): Added a new file detailing licensing practices, including instructions for adding license headers, handling third-party dependencies, and ensuring license compliance.
* …
> chore: W-18839348 - missing required files for ospo compliance
