forcedotcom/salesforcedx-apex

- packages/apex-node/src/execute/executeService.ts
fix an issue in which the command would hang for around 60s even after the apex code was already compiled and executed
fixes one of the issues mentioned in https://github.com/forcedotcom/cli/issues/908
When executing `sfdx force:apex:execute` with user input, the command would hang for around 60s even though the apex code was compiled, executed and its result presented in stdout
command does not hang anymore
>  fix(execute-service): fix 60s hang on apex:execute command

- packages/apex-node/src/streaming/streamingClient.ts
- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/plugin-apex/src/commands/force/apex/test/report.ts
This PR addresses an issue where the force:apex:test:report command would throw an error on test runs that were still in progress. In this PR, we're now matching the previous CLI behavior by subscribing to test runs using the Streaming API and waiting to output the results. Test runs that are already complete should still return the results immediately.
#198, @W-9346853@
> feat: subscribe to test run in progress with test:report command

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
"The dist tag was not found" error (W-9357574) blocked the version bump step in CI.
Manually bump main version.
> chore: updated version 0.2.2

- .circleci/config.yml
Possibly there's a time difference between dist-tags becoming available in https://registry.npmjs.org/@salesforce/plugin-apex and when it’s available in the command `npm dist-tag ls $PKG_NAME`.
@W-9357574@
> fix: query registry for dist tags

- lerna.json
- packages/apex-node/package.json
- packages/plugin-apex/package.json
Manually bump main version to 0.2.3
The version bump failed to get pushed because of [dist-tags issue](https://platformcloud.slack.com/archives/C0171FWUHC1/p1626385351062500). We likely need to directly query the registry https://registry.npmjs.org/@salesforce/plugin-apex instead of running the command `npm dist-tag ls @salesforce/plugin-apex`.
> chore: updated version 0.2.3

- .circleci/config.yml
Fixes dist-tags issue using the approach from https://github.com/forcedotcom/npm-release-management-orb/pull/11/files#diff-3ceb41195ca197a92cc89f6ea51b96bf621a2b02d64105ababd7cf03a279f424R49-R65. 
Migrating to the latest version of npm release management orb would require a bit of work since it no longer has the publish command.
@W-9357574@
> fix: fix dist tags issue

- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/test/commands/force/apex/test/run.test.ts
Fixes output when the wait flag is specified.
@W-9346875@
After running, user was told to run a second command to open the report.
The report is now displayed.
> fix: waitFlag

- packages/apex-node/src/tests/asyncTests.ts
- packages/apex-node/src/tests/codeCoverage.ts
- packages/apex-node/src/tests/constants.ts
- packages/apex-node/src/tests/utils.ts
- packages/apex-node/test/tests/asyncTests.test.ts
- packages/apex-node/test/tests/codeCoverage.test.ts
Fixes issue where a 414 error was being returned when the Apex REST API was called with an URI that was too long.
@W-9179311@
When running `sfdx force:apex:test:run -u oneappexchangeperf -r human -c -l RunLocalTests -w 1440 --verbose` (an org with a large number of Apex tests), a result of `<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>` would be displayed.
The tests now run successfully
> fix: 414-from-long-url

- packages/plugin-apex/src/commands/force/apex/execute.ts
- packages/plugin-apex/src/commands/force/apex/log/get.ts
- packages/plugin-apex/src/commands/force/apex/log/list.ts
- packages/plugin-apex/src/commands/force/apex/log/tail.ts
- packages/plugin-apex/src/commands/force/apex/test/report.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
This change allows the commands to be referenced from other custom plugins and those custom plugins will be able to dynamically reference the flags configured.  Making them "readonly" will ensure that the flags are not altered.
`flagsConfig` were limited to the command classes.
`flagsConfig` are available for easy external use.
> Adjustment to commands to make `flagsConfig` public static readonly

- packages/plugin-apex/src/commands/force/apex/execute.ts
- packages/plugin-apex/src/commands/force/apex/log/get.ts
- packages/plugin-apex/src/commands/force/apex/log/list.ts
- packages/plugin-apex/src/commands/force/apex/log/tail.ts
- packages/plugin-apex/src/commands/force/apex/test/report.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
* Adjustment to commands to make `flagsConfig` public static readonly
This change allows the commands to be referenced from other custom plugins and those custom plugins will be able to dynamically reference the flags configured.  Making them "readonly" will ensure that the flags are not altered.
Co-authored-by: John M. Daniel <imjohnmdaniel@ce-v.com>
Port changes to main
> Port PR to main

- packages/apex-node/package.json
- packages/apex-node/yarn.lock
- packages/plugin-apex/package.json
- packages/plugin-apex/yarn.lock
bumps the version of `@salesforce/core` to fix an issue with the removal of `sfdx-faye` dependency
@W-10315739@
> feat: bump version of @salesforce/core

- contributing/commands.md
- contributing/developing.md
- packages/apex-node/src/tests/types.ts
- packages/plugin-apex/src/commands/force/apex/test/run.ts
- packages/plugin-apex/test/commands/force/apex/test/run.test.ts
Changed apex test run payload to set skipCodeCoverage. When code coverage is not called for,
skipCodeCoverage is now set to true. It is set to false when code coverage is specified. This fixes
an issue where code coverage was being run with every test, because this flag was omitted. Updated
corresponding tests to check for payload change.
VS Code: #3541
@W-10221888@
Code coverage was being run for all tests (can query from the Tooling API with `SELECT Id, TestMethodName FROM ApexCodeCoverage`).
Code coverage is only run in the org when the code coverage flag (-c) is added to the command. Otherwise, it does not run (in both synch and async executions).
> fix: apex code coverage flag

- packages/apex-node/src/tests/syncTests.ts
Adds a guard against perClassCov being referenced when undefined.
@W-10411717@
When running the quick launch feature (open Apex test file in editor, and then click "Debug Test"), formatSyncResults() would eventually get called.  Normally, the test file has a reference to the Apex class being tested and actually tests code within the class, and in this scenario, quick launch works.
However, if the test file doesn't test any Apex code (and as such the code coverage is zero), an exception is thrown.
This change guards against this, and the exception is not thrown, and Quick Launch is allowed to complete.
> fix: added guard against empty coverage

- packages/plugin-apex/package.json
I missed updating the generate:manifest build script on the core v3 upgrade which is blocking a publish.  Updated to use oclif instead of oclif-dev.
> build: update manifest generator to use oclif

- packages/apex-node/package.json
- packages/apex-node/src/reporters/coverageReporter.ts
our DefaultReportOptions doesn't support 2 of the underlying istanbul report options, so they're now excluded/omitted from the TS exports
types for istanbul-reports have to be a regular (non-dev)Dep so that consumers aren't forced to import it
by narrowing the types to what's allowed, we should be able to get cleaner consumers (see https://github.com/salesforcecli/plugin-source/blob/c242908e3d2a12948629d556f36e3b95b5361b67/src/deployCommand.ts#L214)
@W-11590388@
> fix: exclude 2 report options

- .circleci/config.yml
Remove listing git tags from the deploy step of the build to avoid failing due to waiting for user input. 
fix #299
deploy time out 
deploy success
> fix: remove listing git tags in deploy

- package.json
- yarn.lock
* Bumps the @salesforce/core dependency to align with the version used by plugin-apex (the cli plugin) and the version used by @salesforce/command
* Enables the plugin to be built using this library by aligning the dependency versions for each library.
@W-11309523@
> chore: bump core dependency

- package.json
- src/tests/testService.ts
- test/tests/testService.test.ts
- yarn.lock
- Makes it possible to run the specified tests in `sfdx force:apex:test:run ...`
#319 , @W-12436719@
- More than one test method from a same test class couldn't be ran
- More than one test method from a same test class can be successfully ran
> fix: fixed error when running more than one test method from a same test class

- package.json
- yarn.lock
Bump the @salesforce/core dependency from v^5.2.0 to v^5.3.18.  This is needed in order to update @salesforce/source-tracking and @salesforce/source-deploy-retrieve to the latest version and match the version of @salesforce/core.
@W-14441163@
> chore: @salesforce/core v^5.2.0 -> v^5.3.18

- src/reporters/junitReporter.ts
- src/tests/asyncTests.ts
- src/tests/syncTests.ts
- src/utils/dateUtil.ts
- test/reporters/testResults.ts
- test/tests/testData.ts
- test/utils/dateUtil.test.ts
Changes test results start time to be ISO format.  The JUnit reporter still reports the start time property in the locale format.  The `formatStartTime` date utility also has the same default behavior but now also accepts an additional parameter for a date format (ISO or locale).
@W-10226817@
https://github.com/forcedotcom/cli/issues/2220
When a language format other than en_US was used to get the ISO time string from a locale specific time string an error would be thrown.
No error is thrown.  JUnit test start time is still reported in the user locale.  Test results JSON have the start time in ISO format.
> fix: prefer ISO date format

- src/reporters/coverageReporter.ts
- test/reporters/coverageReporter.test.ts
clean https://github.com/forcedotcom/salesforcedx-apex/pull/335/files
> refactor: reduce mutation, honest TS as, reduce => object.fromEntries

- src/execute/executeService.ts
- src/execute/types.ts
- test/execute/executeService.test.ts
Updates the type for the header to be optional and handles when it's not there in code.  Adds a unit test.
[Unexpected error while executing anonymous apex. Cannot read properties of undefined (reading 'DebuggingInfo')#2630](https://github.com/forcedotcom/cli/issues/2630)
@W-14750755@
Throws `Cannot read properties of undefined (reading 'DebuggingInfo')`
<insert gif and/or summary>
apex executes without error
> fix: support when header is not present

- src/streaming/codeCoverageStringifyStream.ts
- src/streaming/testResultStringifyStream.ts
- test/streaming/codeCoverageStringifyStream.test.ts
- test/streaming/jsonStringifyStream.test.ts
- test/streaming/testResultStringifyStream.test.ts
- yarn.lock
fixes a bug that was introduced when making the change to streams for output generation
@W-15471840@
[#5534](https://github.com/forcedotcom/salesforcedx-vscode/issues/5534)
unneeded commas were being inserted into json results
Unneeded commas removed
> fix: dangling commas in json results

- src/streaming/testResultStringifyStream.ts
- test/streaming/testResultStringifyStream.test.ts
@W-15530915@
Fix the edge case to prevent dangling comma when tests are not run with coverage
The vscode-core extension has a setting that lets the cutomer choose if the do not want code coverage calculated when running apex tests. With no coverage data present the code that produces the json results, which are used to highlight coverage in vscode, was inserting a comma after the test results, resulting in an invalid json file.
This fix properly handless tests run with no code coverage present.
> fix: no dangling comma is included in result

- .github/workflows/onRelease.yml
- package.json
- src/execute/executeService.ts
- src/logs/logService.ts
- src/streaming/streamingClient.ts
- src/tests/asyncTests.ts
- src/tests/syncTests.ts
- src/tests/testService.ts
- src/tests/utils.ts
- src/utils/authUtil.ts
- test/execute/executeService.test.ts
- test/logs/logService.test.ts
- test/streaming/streamingClient.test.ts
- test/tests/asyncTests.test.ts
- test/tests/codeCoverage.test.ts
- test/tests/payloadUtil.test.ts
- test/tests/syncTests.test.ts
- test/tests/testService.test.ts
- test/tests/utils.test.ts
- test/utils/fileSystemHandler.test.ts
- test/utils/traceFlags.test.ts
- tsconfig.json
- yarn.lock
> this is published as a beta npm package.  Set the pjson `version` property back where it belongs before merging
now with 80% less jsforce bloat!
use top-levle export for testSetup (requires some tsconfig changes to support node16 module resolution, which changes `import *` stuff
@W-15387805@
> feat!: core7 w/ jsforce-node

- .github/workflows/testCommitExceptMain.yml
- package.json
- yarn.lock
sets up apex-node to run ext-NUTs on PRs
@W-13748495@
no ext NUTs would run on library changes, breaking changes were possible
external NUTs run before changes are merged and released in the library
> ci: setup ext NUTs for apex-node

- .github/workflows/releaseWithCoreBundle.yml
- .github/workflows/testCommitExceptMain.yml
- .github/workflows/testWithCoreBundle.yml
- package.json
- yarn.lock
Implement automation tests with core-bundle
@W-15634776@
Test run: https://github.com/forcedotcom/salesforcedx-apex/actions/runs/9305984148/job/25614186652?pr=371 ✅
> chore: automation test with core bundle

- src/tests/codeCoverage.ts
- src/tests/utils.ts
- test/tests/codeCoverage.test.ts
Populates the "Apex Code Coverage by Class" table in the Apex test results with all Apex classes/triggers listed in the ApexCodeCoverageAggregate Tooling API table when the "Show Only Aggregated Code Coverage" setting is checked.
https://github.com/forcedotcom/salesforcedx-vscode/issues/5599, @W-15783639@
When the "Show Only Aggregated Code Coverage" setting is checked, the "Apex Code Coverage by Class" table in the Apex test results is empty.
```
=== Apex Code Coverage by Class
```
When the "Show Only Aggregated Code Coverage" setting is checked, the "Apex Code Coverage by Class" table in the Apex test results is populated with all available Apex classes/triggers listed in the ApexCodeCoverageAggregate Tooling API table.
```
=== Apex Code Coverage by Class
CLASSES               PERCENT …
```
> fix: All Apex classes/triggers in the ApexCodeCoverageAggregate table are displayed when the "Show Only Aggregated Code Coverage" setting is checked

- package.json
- yarn.lock
bump kit
explanation: I don't know why, but the bundle tests don't seem to like it when you've got different versions of a dependency.  In this situation, it's kit.  The private method it's complaining about hasn't changed in 3 years.  We just made a PR to kit to make it not exist on the class to avoid this in the future.
But the *real* solution to make sure all the bundler tests aren't constantly throwing false positives is to keep your dependencies current (ex: dependabot + automerge gha)
https://github.com/forcedotcom/sfdx-core/actions/runs/9565816018/job/26369656862
needed for @W-10271718@
> fix(deps): bump kit

- package.json
- src/reporters/coverageReporter.ts
- yarn.lock
switch glob library (we use fast-glob in other places in the CLI, not sure about VSCE)
still trying to get that major release out in the CLI.
Running into this kind of thing
https://github.com/salesforcecli/plugin-apex/actions/runs/9751934644/job/26914499114?pr=513#step:8:40
which is a result of some transitive dependencies messing up semver but only for yarn 1.  background
https://github.com/isaacs/node-glob/issues/563
https://github.com/isaacs/node-glob/issues/566
> fix: switch glob libraries

- src/utils/elapsedTime.ts
- test/tests/elapsedTime.test.ts
Replaces process.hrtime() calls with globalThis.performance.now() 
@W-19127872@
hrtime usage 1
hrtime usage 0
> W-19127872: Remove hrtime
